version: '2'

services:
  opensips:
    env_file: .env
    restart: always

    build:
      context: ./opensips
      dockerfile: Dockerfile
      args:     # Add build arguments
        APP_HOME: app
        OPENSIPS_BUILD : releases
        OPENSIPS_VERSION : 3.3
        OPENSIPS_CLI : 1
        OPENSIPS_EXTRA_MODULES : opensips-mysql-module
        HOST_IP : ${HOST_IP}
    expose:
     - "3306/tcp"
    ports:
     - "5060:5060/udp"


  backend:
    
    restart: always
    environment:
      HOST_IP: opensips

    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        HOST_IP: ${HOST_IP}

    ports:
      - "80:80"
    links:
      - "opensips"
    depends_on:
      - opensips